---
#local home dir
local_home: "{{ lookup('env','HOME') }}"
hostname: "nokiasnap"

#elastic search setup stuff  
elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_download_url: https://artifacts.elastic.co/downloads/elasticsearch
elasticsearch_version: 5.0.0
#elasticsearch_version: 2.4.1
#elasticsearch_download_url: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/{{elasticsearch_version}}
elasticsearch_max_open_files: 65536
elasticsearch_home_dir_prefix: /opt
elasticsearch_home_dir: "{{ elasticsearch_home_dir_prefix }}/elasticsearch"
elasticsearch_plugin_dir: "{{ elasticsearch_home_dir }}/plugins"
## From 5.0 put the config in s
elasticsearch_conf_dir: "{{ elasticsearch_home_dir}}/config"
elasticsearch_pid_dir: /var/run


#elastic search config stuff
elasticsearch_network_host: 0.0.0.0
elasticsearch_http_port: 9200
elasticsearch_heap_size: 1g
elasticsearch_vm_swapiness: 1

elasticsearch_index_data: "/var/snap_data/es_data"
elasticsearch_logs: "/var/snap_logs/es_logs"
elasticsearch_tmp_files: "/tmp/es_tmp"
elasticsearch_service_state: started

elasticsearch_cluster_name: "SNAP"
elasticsearch_is_master: "true"
elasticsearch_is_data: "true"

elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_max_locked_memory: "unlimited"

elasticsearch_discovery_zen_minimum_master_nodes: 1
elasticsearch_discovery_zen_ping_timeout: 30s
elasticsearch_discovery_zen_ping_multicast_port: 54328
elasticsearch_discovery_zen_ping_multicast_enabled: "false"

elasticsearch_discovery_zen_fd_ping_interval: 1s
elasticsearch_discovery_zen_fd_ping_timeout: 30s
elasticsearch_discovery_zen_fd_ping_retries: 3


# kibana config info
kibana_user: kibana
kibana_group: kibana
kibana_download_url: https://artifacts.elastic.co/downloads/kibana
#kibana_download_url: http://download.elastic.co/kibana/kibana
#kibana_version: 4.6.2
kibana_version: 5.0.0
kibana_dir: "/opt"
kibana_host: 0.0.0.0
kibana_port: "5601"
kibana_elasticsearch: "http://localhost:9200"
kibana_index: ".kibana"
kibana_log: "/var/snap_logs/kibana_log"
kibana_log_rotate_count: 5
kibana_log_rotate_interval: daily
kibana_nice_level: "0"
kibana_plugins: []
kibana_config: {}
kibana_username: "admin"
kibana_pass: "admin"

#nginx config
nginx_user: kibana
nginx_port: 80
nginx_worker_connections: 10
nginx_keepalive_timeout: 65
nginx_error_log: "/var/snap_logs/nginx_error.log"
