---
- name: supervisord setup | ensure supervisord is installed
  pip: 
    name=supervisor
    state=latest
  tags: supervisord

- name: supervisord setup | ensure directories are created
  file: 
    state=directory
    dest={{ item }}
    mode=0755
  with_items:
    - "{{ supervisord_log_dir }}"
    - "{{ supervisord_programs_dir }}"
  tags: supervisord
  sudo: yes

- name: supervisord setup | setup configuration
  template:
    src=supervisord.conf.j2
    dest=/etc/supervisord.conf
  tags: supervisord

- name: supervisord setup | setup CentOS supervisord service script
  copy:
    src=supervisord_centos
    dest=/etc/init.d/supervisord
    owner=root
    group=root
    mode=0755
  tags: supervisord
  when: ansible_os_family == "RedHat"

- name: supervisord setup | setup Ubuntu supervisord service script
  copy:
    src=supervisord_ubuntu
    dest=/etc/init.d/supervisord
    owner=root
    group=root
    mode=0755
  tags: supervisord
  when: ansible_os_family == "Debian"

- name: supervisord setup | ensure supervisord is running
  service:
    name: supervisord
    state: started
  tags: supervisord
  sudo: yes

- name: supervisord setup |ensure supervisord starts on boot
  service:
    name: supervisord
    enabled: yes
  tags: supervisord
  sudo: yes
  
- name: supervisord setup | Set fact supervisord_has_run
  set_fact:
    supervisord_has_run: true
